name: Backend CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run Tests
        run: |
          ./mvnw clean test jacoco:report

      - name: Jacoco Report to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: './target/site/jacoco/jacoco.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Spring Boot Backend Coverage
          update-comment: true